version: '3.7'

services:
  web:
    build: .
    command: python3.8 main.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8080:8080
#    env_file:
#      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weather_role
      - POSTGRES_PASSWORD=weather_password
      - POSTGRES_DB=weather_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: